# Generated by Django 5.2.4 on 2025-07-31 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Films',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_film', models.CharField(max_length=50)),
                ('realisateur', models.CharField(max_length=50)),
                ('date_sortie', models.DateField()),
                ('duree', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Livres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_livre', models.CharField(max_length=50)),
                ('auteur', models.CharField(max_length=50)),
                ('date_sortie', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_serie', models.CharField(max_length=50)),
                ('realisateur', models.CharField(max_length=50)),
                ('date_sortie', models.DateField()),
                ('duree', models.IntegerField()),
            ],
        ),
    ]
