# Generated by Django 5.1.6 on 2025-07-31 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='date_sortie',
        ),
        migrations.RemoveField(
            model_name='series',
            name='duree',
        ),
        migrations.AlterField(
            model_name='films',
            name='date_sortie',
            field=models.IntegerField(),
        ),
    ]
