# Generated by Django 5.1.6 on 2025-07-31 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0002_remove_series_date_sortie_remove_series_duree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livres',
            name='date_sortie',
            field=models.IntegerField(),
        ),
    ]
