# Generated by Django 5.1.6 on 2025-07-31 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0003_alter_livres_date_sortie'),
    ]

    operations = [
        migrations.AddField(
            model_name='films',
            name='img_film',
            field=models.ImageField(blank=True, null=True, upload_to='films/'),
        ),
        migrations.AddField(
            model_name='livres',
            name='img_livre',
            field=models.ImageField(blank=True, null=True, upload_to='livres/'),
        ),
        migrations.AddField(
            model_name='series',
            name='img_serie',
            field=models.ImageField(blank=True, null=True, upload_to='series/'),
        ),
    ]
