# Generated by Django 5.1.6 on 2025-08-02 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0004_films_img_film_livres_img_livre_series_img_serie'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='date_premiere_diffusion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='nb_saison',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
