# Generated by Django 5.1.6 on 2025-08-04 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0005_series_date_premiere_diffusion_series_nb_saison'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='films',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='films',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
