# Generated by Django 5.1.6 on 2025-08-04 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0006_alter_films_options_films_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='series',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='series',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
